###############################################################
#  Generated by:      Cadence Innovus 17.13-s098_1
#  OS:                Linux x86_64(Host ID cadence)
#  Generated on:      Sat May  4 17:24:14 2019
#  Design:            Array
#  Command:           saveDesign Array.enc
###############################################################
current_design Array
