###############################################################
#  Generated by:      Cadence Innovus 17.13-s098_1
#  OS:                Linux x86_64(Host ID cadence)
#  Generated on:      Sat May  4 16:54:40 2019
#  Design:            Wallace
#  Command:           saveDesign Wallace.enc
###############################################################
current_design Wallace
